### ISSUE TITLE
Timestamp Binance

### ISSUE THREAD

**Issue by Yoganesh** [aloysius-pgast/crypto-exchanges-gateway#11]
Hi,

Thank you for this awesome tool..it is looking very promising!

Do you know how I can fix this timestamp issue I am getting with Binance please?

My timezone is CEST..

1507337786396|ERROR|{"exchange":"binance","api":"allOrders","pair":"BTC-CTR"} => {"code":-1021,"msg":"Timestamp for this request is not valid."}

**Comment by aloysius-pgast** [comment]
Hi. Thanks for your feedback. I think it has something to do with clock skew (ie: your clock my be behind Binance's one). In order to verify this, could you connect to https://www.timeanddate.com/worldclock/, check correct time for your timezone and fix the deviation ?.

Binance does following check (this is from Binance documentation

```
if (timestamp < serverTime && (serverTime - timestamp) <= recvWindow) {
  // process request
} else {
  // reject request
}
```
So if time on your PC is behind time on Binance for more than recvWindow (which is 5000 ms by default), request will be rejected

 I added a new parameter in config.json to be able to configure this value (default = 5000)

```
...
        "binance":{
            "enabled":true,
            "recvWindow":5000,
            ...
            }
        }
...
```
In order to use it , you should do the following :
* checkout dev branch 
```
git checkout dev
```
* pull changes
```
git pull
```
* retrieve last version of my binance module
```
rm -fr node_modules/binance
npm install
```
* update config.json with new parameter _recvWindow_
```
* restart gateway

Also keep in mind that this has to be seen as a workaround which won't work if your clock is ahead of time. So in order to fix it definitely, you should try to resync your clock

Let me know if you still have problems after that

**Comment by Yoganesh** [comment]
Working great. Thanks for your help!
