### ISSUE TITLE
support for all open orders

### ISSUE THREAD

**Issue by pipinoloco** [aloysius-pgast/crypto-exchanges-gateway#26]
What a cool project, congratulations.
i want to have the feature to watch all the open orders besides starred pairs and also support for BNB pairs on binance.
best regards.

**Comment by aloysius-pgast** [comment]
Thanks for your support. In first versions of the project, it used to be possible. At that time Binance did not offer an API to retrieve all open orders at once so such request meant  iterating over all possible pairs and check open orders for each pair. Since they now support =~ 250 pairs and request limit for orders is 10/seconds I had to choose between waiting 30s before displaying open orders or taking the risk of Binance banning the ip. I'm working on a way to work around this. In the meantime, I advise you mark the pairs you trade as favorite so that they can be listed in open orders

**Comment by aloysius-pgast** [comment]
Also, BNB pairs should now be listed (check the [develop](https://github.com/aloysius-pgast/crypto-exchanges-gateway/tree/develop) branch)
