### ISSUE TITLE
Bug in your websocket connection file + a few fixes

### ISSUE THREAD

**Issue by slidenerd** [aloysius-pgast/crypto-exchanges-gateway#65]
Line 182 websocket connection.js file

```
                   let interval = setInterval(function () {
                            if (WebSocket.OPEN != _ws.readyState) {
                                clearTimeout(interval);
                                return;
                            }
                            if (!_ws.isAlive) {
                                if (debug.enabled) {
                                    debug("WS (%s) timeout : timeout = %d", self._uri, self._pingTimeout);
                                }
                                _ws.terminate();
                                clearTimeout(interval);
                                return;
                            }
                            _ws.isAlive = false;
                            if (debug.enabled) {
                                debug("Sending WS PING (%s)", self._uri);
                            }
                            _ws.ping('', true, true);
                        }, self._pingTimeout);
```

You are calling **setInterval** but you are calling **clearTimeout** which may or may not be compatible all the time
A few questions

- What is the purpose of this? **ignoreCloseEvent**, you are setting it to true in the constructor and finalize but setting it to false inside open callback. The only purpose I see is when the close event is fired, you are checking if you should ignore it and return prematurely, when would you ever enter that if statement?

- Also why do we need to skipCloseEvent

- No need to add doRetry either :) 

- Another thing you might wanna consider is doing a noop ping instead of the true you are sending currently, seems to be standard practice https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L285

- Also can you replace your function callbacks with arrow functions, it will replace all the self=this calls

**Comment by aloysius-pgast** [comment]
Hi. Thanks for your comments. 

I'm not sure exactly what the bug you're referring to is (could you describe it ? ;)). Regarding your questions, here's my answers  :

1) clearTimeout / clearInterval

You're probably right as for consistency I should use _clearInterval_ but nodejs will handle it properly as explained in https://nodejs.org/api/timers.html#timers_class_timeout

> This object is created internally and is returned from setTimeout() and setInterval(). It can be passed to either clearTimeout() or clearInterval() in order to cancel the scheduled actions

2) ignoreCloseEvent

This is set to false when ws is opened, since close events should be handled. But if ws is explicitely closed by calling [disconnect](https://github.com/aloysius-pgast/crypto-exchanges-gateway/blob/develop/app/websocket-connection.js#L127) method, event will be ignored

3) skipCloseEvent

It is needed since in case _error_ event is triggered, there is no need to also handle the _close_ event

4) doRetry

It is also necessary since in case a connection error occurs, [function](https://github.com/aloysius-pgast/crypto-exchanges-gateway/blob/develop/app/websocket-connection.js#L171) will be retried automatically up to 10 times (I can tell you that sometimes it can take multiple retries before connection is established). See https://github.com/tim-kos/node-retry for information regarding _retry_ library

5) Noop ping

If you check the [code](https://github.com/websockets/ws/blob/master/lib/websocket.js#L239) for ping method, you will notice that when doing [ws.ping(noop)](https://github.com/jaggedsoft/node-binance-api/blob/master/node-binance-api.js#L285) _ws_ library will actually do a _ping('', true)_ and call the noop callback. Also in the version 3.2.0 (which is used by the gateway), the prototype of [ping method](https://github.com/websockets/ws/blob/3.2.0/lib/WebSocket.js#L305) is a bit different and does not accept a callback. For the moment, I don't see any reason to change the version used by gateway. 

6) Arrows

This would make code clearer I agree. Will keep it in mind.

**Comment by slidenerd** [comment]
Awesome!!! Thanks for all the replies, I am closing this issue :)

**Comment by slidenerd** [comment]
I am sorry if this sounds like a silly question but I had to ask, you seem to be creating a different websocket inside the session file but for each exchange you have a stream client and an exchange class which seems to be used by subscription manager of that exchange which in turn is used inside the routes file for that exchange, when I go to gateway.js, it seems to trigger startWs inside ws/main.js which in turn manages uses the websocket inside the session object, where and how does routes/subscription manager tie into this and more importantly, can you directly use the routes without the whole session, registry and storage thingies
