### ISSUE TITLE
In Localhost installation, can only view "prices", & Order Books

### ISSUE THREAD

**Issue by LogeswaranAudhikesavan** [aloysius-pgast/crypto-exchanges-gateway#68]
Hi - First of all, this is wonderful piece of work, thanks for extending it to community. I have gone through the installation instructions & did setup in my ubuntu machine(localhost), went fine with no errors, Was able to build UI & triggered it. But in UI, i can only view "order books" & "Prices" in all exchanges, not more than that. Where as in Demo Link, I can see we have many other options such as "New Order", "My Order", "MY balances"

Thanks,
Lokesh

**Comment by aloysius-pgast** [comment]
Hi. Thanks for your interest :)

In order to enable menus related to trading (New Order, My Order ...), you need to provide *key* & *secret* (for the exchanges you want to enables those features) in *config.json*. See details about config file at https://github.com/aloysius-pgast/crypto-exchanges-gateway/blob/master/doc/config.adoc. If you don't want to provide your real credentials, you can set both *key* & *secret* to *demo* and gateway will generate fake data, like it does on the demo url

Hope it helps.

**Comment by LogeswaranAudhikesavan** [comment]
that's awesome, it worked like a charm!!, you guys rock. I am interested to contribute!! :)

**Comment by LogeswaranAudhikesavan** [comment]
Yes I am fine with python or PHP. Glad to be part of this :)

**Comment by aloysius-pgast** [comment]
Great. Let me know when you have something ready, so that I can add a link to it in the readme.
