### ISSUE TITLE
Filter trade notifications to only emit my exchange's account trades

### ISSUE THREAD

**Issue by lolero** [aloysius-pgast/crypto-exchanges-gateway#88]
When run the docker container with my key and my secret and I subscribe to a pair's trades, I get notifications for, I think, all the trades that take place for that pair.

Would it be possible to only emit notification of trades that correspond to orders placed by me?

**Comment by aloysius-pgast** [comment]
Hi. Trades subscriptions is for all trades happening for a given pair. It uses public endpoint (ie: it does not need any secret key). Right now there is no ws support to retrieve your own order, although you could periodically retrieve the list of open & closed orders using http endpoint instead of ws endpoint

**Comment by lolero** [comment]
ok.  thanks!

just for general info, is there a plan to add subscription functionality for orders?

**Comment by aloysius-pgast** [comment]
Yes, I planned to implement such feature but unfortunately I didn't have time to work on it. I hope to resume work on it but I don't think it will happen in the next 6 months. That's why I suggested you to use REST api periodically. This is what I'm using myself for automate trading : 
* place an order
* save order id (in db for example)
* periodically check if order status changed (not too often to be under exchange limits, for example every 5 min)
* if order has been filled, use [POST /pushover/notify](https://github.com/aloysius-pgast/crypto-exchanges-gateway/blob/master/doc/pushover/notifications.adoc#send-a-notification) endpoint to send me a mobile notification

**Comment by lolero** [comment]
Cool, thanks!  Im actually going to wait for a trade notification in that pair to happen before I query the http endpoint so I don't have to poll.
That will work fine for now, I think.  But I look forward to your implementation.
Thanks a lot for your hard work. If I am able to make any money out of this, I'll make sure to make a donation!

**Comment by aloysius-pgast** [comment]
If you check every 5min `GET /exchanges/{exchangeId}/openOrders` for a given pair (ex: `GET /exchanges/binance/openOrders/?pairs=USDT-BTC`), you will stay within the limits without problem (the gateway will rate-limit every request to comply with exchange limits but it's better to also limitrequest on your side). 

And if you want to check the status of a particular order, you can use `GET /exchanges/{exchangeId}/{orderNumber}` (ex: `GET /exchanges/binance}/orders/xxxxxx/?pairs=USDT-BTC` where `xxxxxx` is the order number)

Hope you will manage to do what you're trying to achieve ;)
